//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AirCaddy.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class PrivilegeRequest
    {
        public int Id { get; set; }
        public string GolfCourseName { get; set; }
        public string GolfCourseAddress { get; set; }
        public string CoursePhoneNumber { get; set; }
        public string Reason { get; set; }
        public bool Verified { get; set; }
        public string UserId { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
    }
}
